#!/usr/bin/env bash
# Display information about the subdomains

subdomain () {
    fetch_info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $fetch_info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  subdomain "$1" "www"
  subdomain "$1" "lb-01"
  subdomain "$1" "web-01"
  subdomain "$1" "web-02"
elif [ "$#" == 2 ]
then
  subdomain "$1" "$2"
fi
