#!/usr/bin/env bash
# Install the web server 'nginx' on the server and perform some configurations
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

new_website=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }

        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"
echo "$new_website" > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
