#!/usr/bin/env bash
# Install/configure the load balancer, 'HAproxy'

apt-get update -y
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.6 -y
apt-get install haproxy=2.6.\* -y

my_config=\
"
# My configuration for my servers
frontend tmaworldwide
	bind *:80
	mode http
	default_backend tma_backend
	backend tma_backend
	balance roundrobin
	server 52468-web-01 100.25.138.198:80 check
	server 52468-web-02 54.146.14.176:80 check
"
echo "$my_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy restart
