#!/usr/bin/env bash
# Install/configure the load balancer, 'HAproxy'

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 52468-web-01 100.25.138.198:80 check\n\tserver 52468-web-02 54.146.14.176:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
